//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int IdAdresu { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string NumerUlicy { get; set; }
        public int IdWypozyczalni { get; set; }
    
        public virtual Wypozyczalnia Wypozyczalnia { get; set; }
    }
}
