//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProjekt
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Samochod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochod()
        {
            this.Wypozyczenie = new ObservableCollection<Wypozyczenie>();
        }
    
        public int IdSamochodu { get; set; }
        public string MarkaSamochodu { get; set; }
        public string ModelSamochodu { get; set; }
        public Nullable<int> RokProduckji { get; set; }
        public int IdWypozyczalni { get; set; }
        public int CenaZaDzien { get; set; }
        public bool Dostepnosc { get; set; }
        public string VIN { get; set; }
    
        public virtual Wypozyczalnia Wypozyczalnia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wypozyczenie> Wypozyczenie { get; set; }
    }
}
