//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        public int IdWypożyczenia { get; set; }
        public int IdKlienta { get; set; }
        public int IdSamochodu { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Samochod Samochod { get; set; }
    }
}
